// ═══════════════════════════════════════════════════
// GOOGLE SHEETS — Column mappings & helper functions
// ═══════════════════════════════════════════════════

// ── Helper: Convert column index (0-based) to Excel letter(s) ──
export function colLetter(index: number): string {
  let letter = "";
  let n = index + 1;
  while (n > 0) {
    const remainder = (n - 1) % 26;
    letter = String.fromCharCode(65 + remainder) + letter;
    n = Math.floor((n - 1) / 26);
  }
  return letter;
}

// ── Helper: Build range string for a sheet ──
export function sheetRange(sheetName: string, numColumns: number): string {
  return `${sheetName}!A2:${colLetter(numColumns - 1)}`;
}

// ── Sheet Names ──
export const SHEETS = {
  Dimensions: "Dimensions",
  DimensionValues: "Dimension_Values",
  DefaultDimensions: "Default_Dimensions",
  ChartOfAccounts: "Chart_of_Accounts",
  Clients: "Clients",
  Vendors: "Vendors",
  Items: "Items",
  SalesInvoices: "Sales_Invoices",
  PurchaseInvoices: "Purchase_Invoices",
  GeneralLedger: "General_Ledger",
  Subledger: "Subledger",
  Employees: "Employees",
  TaxRates: "Tax_Rates",
  Payroll: "Payroll",
  CreditCards: "Credit_Cards",
  CCTransactions: "CC_Transactions",
  BankAccounts: "Bank_Accounts",
  BankTransactions: "Bank_Transactions",
  SalesReceipts: "Sales_Receipts",
  Payments: "Payments",
} as const;

// ── Dimension column headers (appended to most sheets) ──
export const DIMENSION_HEADERS = [
  "Dimension_1",
  "Dimension_2",
  "Dimension_3",
  "Dimension_4",
  "Dimension_5",
  "Dimension_6",
  "Dimension_7",
  "Dimension_8",
  "Account_No",
];

// ── Column Headers per Sheet ──
export const SHEET_HEADERS: Record<string, string[]> = {
  [SHEETS.Dimensions]: [
    "Dim_Slot",
    "Dimension_Code",
    "Dimension_Name",
    "Description",
    "Is_Required",
    "Is_Active",
    "Default_Value",
    "Blocking_Rule",
    "Created_Date",
    "Notes",
  ],
  [SHEETS.DimensionValues]: [
    "DimValue_ID",
    "Dim_Slot",
    "Dimension_Code",
    "Value_Code",
    "Value_Name",
    "Parent_Value_Code",
    "Dimension_Type",
    "Totaling",
    "Blocked",
    "Is_Active",
    "GL_Account_Filter",
    "Created_Date",
    "Notes",
  ],
  [SHEETS.DefaultDimensions]: [
    "DefaultDim_ID",
    "Table_Name",
    "Record_ID",
    "Dim_Slot",
    "Dimension_Code",
    "Value_Code",
    "Value_Posting_Rule",
    "Notes",
  ],
  [SHEETS.ChartOfAccounts]: [
    "Account_Code",
    "Account_Name",
    "Account_Type",
    "Sub_Category",
    "Is_Active",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.Clients]: [
    "Client_ID",
    "Company_Name",
    "Contact_Name",
    "Email",
    "Phone",
    "Address",
    "Tax_ID",
    "Payment_Terms",
    "Balance",
    "Status",
    "Created_Date",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.Vendors]: [
    "Vendor_ID",
    "Company_Name",
    "Contact_Name",
    "Email",
    "Phone",
    "Address",
    "Tax_ID",
    "Payment_Terms",
    "Default_Category",
    "Balance",
    "Status",
    "Created_Date",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.Items]: [
    "Item_ID",
    "Item_Name",
    "Description",
    "Unit_Price",
    "Cost_Price",
    "Tax_Rate",
    "Account_Code",
    "Category",
    "Unit",
    "Is_Active",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.SalesInvoices]: [
    "Invoice_ID",
    "Client_ID",
    "Invoice_Date",
    "Due_Date",
    "Line_Items",
    "Subtotal",
    "Tax_Amount",
    "Total_Amount",
    "Amount_Paid",
    "Balance_Due",
    "Status",
    "GL_Posted",
    "PDF_URL",
    "Notes",
    "Created_By",
    "Approved_By",
    "Approved_Date",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.PurchaseInvoices]: [
    "PurchInv_ID",
    "Vendor_ID",
    "Vendor_Name",
    "Vendor_Invoice_No",
    "Invoice_Date",
    "Due_Date",
    "Line_Items",
    "GL_Account_Code",
    "GL_Account_Name",
    "Subtotal",
    "Tax_Amount",
    "Tax1_Amount",
    "Tax2_Amount",
    "Total_Amount",
    "Amount_Paid",
    "Balance_Due",
    "Status",
    "GL_Posted",
    "PDF_URL",
    "Document_Name",
    "Source_Email",
    "Received_Date",
    "Approved_By",
    "Approved_Date",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.GeneralLedger]: [
    "GL_ID",
    "Date",
    "Account_Code",
    "Account_Name",
    "Description",
    "Reference",
    "Debit",
    "Credit",
    "Balance",
    "Client_ID",
    "Category",
    "Source_Module",
    "Posted_Date",
    "Posted_By",
    "Subledger_ID",
    "Source_Doc_URL",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.Subledger]: [
    "SL_ID",
    "Posting_Date",
    "Document_Date",
    "Document_No",
    "Document_Type",
    "Entity_Type",
    "Entity_ID",
    "Entity_Name",
    "Account_Code",
    "Account_Name",
    "Item_No",
    "Item_Description",
    "Qty",
    "Price",
    "Amount",
    "Tax_Code",
    "Tax_Amount",
    "Debit",
    "Credit",
    "GL_ID",
    "Client_ID",
    "Source_Doc_URL",
    "Source_Input",
    "Posted_By",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.Employees]: [
    "Employee_ID",
    "First_Name",
    "Last_Name",
    "Email",
    "Phone",
    "Address",
    "SIN",
    "Date_of_Birth",
    "Hire_Date",
    "Position",
    "Hourly_Rate",
    "Pay_Frequency",
    "Province",
    "Status",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.TaxRates]: [
    "Tax_Code",
    "Tax_Name",
    "Rate",
    "Province",
    "Effective_Date",
    "Expiry_Date",
    "GL_Account_Code",
    "Is_Active",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.Payroll]: [
    "Payroll_ID",
    "Employee_ID",
    "Pay_Period_Start",
    "Pay_Period_End",
    "Hours_Worked",
    "Hourly_Rate",
    "Gross_Pay",
    "Federal_Tax",
    "Provincial_Tax",
    "CPP_QPP_Employee",
    "CPP_QPP_Employer",
    "EI_Employee",
    "EI_Employer",
    "QPIP_Employee",
    "QPIP_Employer",
    "Other_Deductions",
    "Net_Pay",
    "Status",
    "GL_Posted",
    "Pay_Date",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.CreditCards]: [
    "CC_ID",
    "Card_Name",
    "Card_Number_Last4",
    "Credit_Limit",
    "Current_Balance",
    "GL_Account_Code",
    "Status",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.CCTransactions]: [
    "CCT_ID",
    "CC_ID",
    "Transaction_Date",
    "Description",
    "Amount",
    "Category",
    "Account_Code",
    "Vendor_Match",
    "GL_Posted",
    "Status",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.BankAccounts]: [
    "Bank_ID",
    "Bank_Name",
    "Account_Name",
    "Account_Number_Last4",
    "Current_Balance",
    "GL_Account_Code",
    "Status",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.BankTransactions]: [
    "BT_ID",
    "Bank_ID",
    "Transaction_Date",
    "Description",
    "Debit",
    "Credit",
    "Balance",
    "Category",
    "Account_Code",
    "Matched_Reference",
    "GL_Posted",
    "Status",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.SalesReceipts]: [
    "Receipt_ID",
    "Client_ID",
    "Invoice_ID",
    "Receipt_Date",
    "Amount",
    "Payment_Method",
    "Reference_Number",
    "Bank_ID",
    "Status",
    "GL_Posted",
    "SL_Posted",
    "Source_Doc_URL",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
  [SHEETS.Payments]: [
    "Payment_ID",
    "PurchInv_ID",
    "Vendor_ID",
    "Payment_Date",
    "Amount",
    "Payment_Method",
    "Reference_Number",
    "Status",
    "GL_Posted",
    "SL_Posted",
    "Source_Doc_URL",
    "Notes",
    ...DIMENSION_HEADERS,
  ],
};
