import { NextRequest } from "next/server";
import { ok, error } from "@/lib/utils/api-helpers";
import { sendEmail } from "@/lib/google/gmail";
import { listAccounts } from "@/lib/google/accounts";
import { runWithTenant } from "@/lib/tenant/context";
import { buildDailySummary, DailySummary } from "@/lib/reports/daily";
import { today } from "@/lib/utils/date";
import { runHealthChecks, healthHtml, pingWatchdog } from "@/lib/health/checks";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
// One report per tenant; each reads several sheets.
export const maxDuration = 60;

const money = (n: number) =>
  n.toLocaleString("en-CA", { style: "currency", currency: "CAD" });

function digestHtml(report: DailySummary): string {
  const rows: [string, string][] = [
    ["Sales today", money(report.summary.totalSales)],
    ["Purchases today", money(report.summary.totalPurchases)],
    ["Received", money(report.summary.totalReceived)],
    ["Paid out", money(report.summary.totalPaid)],
    ["Net cash flow", money(report.summary.netCashFlow)],
    ["Overdue invoices", `${report.overdueAR.count} (${money(report.overdueAR.total)})`],
  ];

  return `
    <h2>SoulLogic Daily Digest — ${report.date}</h2>
    <table cellpadding="8" style="border-collapse:collapse;width:100%;max-width:500px">
      ${rows
        .map(
          ([label, value], i) => `
        <tr${i % 2 === 0 ? ' style="background:#f3f4f6"' : ""}>
          <td><strong>${label}</strong></td>
          <td style="text-align:right">${value}</td>
        </tr>`
        )
        .join("")}
    </table>
    <p style="margin-top:16px;font-size:12px;color:#6b7280">
      Generated by SoulLogic AI Accountant at ${new Date().toISOString()}
    </p>
  `;
}

export async function GET(req: NextRequest) {
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return error("Unauthorized", 401);
  }

  try {
    const date = today();
    const accounts = await listAccounts();
    const sent: string[] = [];
    const failed: string[] = [];

    for (const account of accounts) {
      try {
        // Each tenant's figures are computed against that tenant's own book.
        const report = await runWithTenant(
          { accountNo: account.Account_No, spreadsheetId: account.Spreadsheet_ID },
          () => buildDailySummary(date)
        );

        await sendEmail(
          account.Email,
          `SoulLogic Daily Digest — ${date}`,
          digestHtml(report)
        );
        sent.push(account.Account_No);
      } catch (acctErr) {
        // One tenant's failure must not stop the rest of the run.
        console.error(`Daily report failed for ${account.Account_No}:`, acctErr);
        failed.push(account.Account_No);
      }
    }

    // Health goes to the operator, not to customers: a revoked share or an
    // expired token is not a tenant's problem to read about.
    const health = await runHealthChecks();
    const operator = process.env.ALERT_EMAIL ?? process.env.GMAIL_MONITOR_ADDRESS;
    if (operator) {
      const broken = !health.ok || failed.length > 0;
      await sendEmail(
        operator,
        `${broken ? "[ACTION NEEDED] " : ""}SoulLogic pipeline — ${date}`,
        `${healthHtml(health)}
         <p>Digests sent: ${sent.length}${failed.length ? `, failed for ${failed.join(", ")}` : ""}</p>
         ${broken ? "<p><strong>Something needs attention above.</strong></p>" : "<p>Everything nominal.</p>"}`
      ).catch((err) => console.error("[daily-report] operator alert failed:", err));
    }
    await pingWatchdog(health.ok && failed.length === 0 ? "ok" : "fail", "report");

    return ok({
      date,
      sent: sent.length,
      failed: failed.length,
      failedAccounts: failed,
      health: { ok: health.ok, failing: health.failing.map((c) => c.name) },
    });
  } catch (err) {
    console.error("Daily report cron error:", err);
    return error("Failed to send daily reports");
  }
}
