import { NextRequest } from "next/server";
import { ok, error } from "@/lib/utils/api-helpers";
import { sendEmail } from "@/lib/google/gmail";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(req: NextRequest) {
  // Verify Vercel cron secret
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return error("Unauthorized", 401);
  }

  try {
    // Fetch daily report data
    const baseUrl = process.env.NEXTAUTH_URL ?? "http://localhost:3000";
    const reportRes = await fetch(`${baseUrl}/api/reports/daily`, {
      headers: { "x-internal": "cron" },
    });
    const report = await reportRes.json();
    const data = report.data ?? {};

    const recipientEmail = process.env.DAILY_REPORT_EMAIL;
    if (!recipientEmail) {
      return ok({ skipped: true, reason: "DAILY_REPORT_EMAIL not set" });
    }

    const html = `
      <h2>SoulLogic Daily Digest — ${new Date().toLocaleDateString("en-CA")}</h2>
      <table cellpadding="8" style="border-collapse:collapse;width:100%;max-width:500px">
        <tr style="background:#f3f4f6">
          <td><strong>Revenue MTD</strong></td>
          <td style="text-align:right">${(data.revenue_mtd ?? 0).toLocaleString("en-CA", { style: "currency", currency: "CAD" })}</td>
        </tr>
        <tr>
          <td><strong>AR Balance</strong></td>
          <td style="text-align:right">${(data.ar_balance ?? 0).toLocaleString("en-CA", { style: "currency", currency: "CAD" })}</td>
        </tr>
        <tr style="background:#f3f4f6">
          <td><strong>AP Balance</strong></td>
          <td style="text-align:right">${(data.ap_balance ?? 0).toLocaleString("en-CA", { style: "currency", currency: "CAD" })}</td>
        </tr>
        <tr>
          <td><strong>Cash Balance</strong></td>
          <td style="text-align:right">${(data.cash_balance ?? 0).toLocaleString("en-CA", { style: "currency", currency: "CAD" })}</td>
        </tr>
        <tr style="background:#f3f4f6">
          <td><strong>Overdue Invoices</strong></td>
          <td style="text-align:right">${data.overdue_count ?? 0}</td>
        </tr>
      </table>
      <p style="margin-top:16px;font-size:12px;color:#6b7280">
        Generated by SoulLogic AI Accountant at ${new Date().toISOString()}
      </p>
    `;

    await sendEmail(
      recipientEmail,
      `SoulLogic Daily Digest — ${new Date().toLocaleDateString("en-CA")}`,
      html
    );

    return ok({ sent: true, to: recipientEmail });
  } catch (err) {
    console.error("Daily report cron error:", err);
    return error("Failed to send daily report");
  }
}
